### ISSUE TITLE
[Feature request] SPUtility.SendEmail

### ISSUE THREAD

**Issue by Zireael** [Aymkdn/SharepointPlus#115]
Hi, Thank you for SharepointPlus
I have a feature request - would it be possible to add **SPUtility.SendEmail** functionality?
Basically being able to send email notifications programmatically. I know you can set a workflow to send email, but there are situations where doing so through JS would be more convenient.
Like, putting together a more complicated email template in a workflow designer with some styling and variables mixed in is a nightmare (been there, done that).

Here's a quick overview of the native function:
https://collab365.community/sending-email-programmatically-in-sharepoint/

Thanks in advance!

**Comment by Aymkdn** [comment]
Hi,

There is already an easy to use REST API function for that: https://sharepoint.stackexchange.com/questions/148226/send-e-mail-from-javascript-using-rest-api

Personally, I prefer to create a list called "Emails" with 4 columns : 

1. To (people picker)
2. Cc (people picker)
3. Subject
4. Body (rich text)

Then I have a workflow that sends the email as soon as a new item is added into that list. Like that I can enter whatever I want in `Body` and it will be sent (I have also a list "Email Templates" that I can dynamic get, fill and send to `Emails` list). I just use :
```javascript
$SP().list("Emails").add({
  To:"john.doe@company.com",
  Title:"Hello World",
  Body:"This is a <b>bold</b> and <em>italic</em> text."
})
```
It's also good to have this kind of list, because you can keep track of the emails sent, and people cannot say "I never received an email from the tool!" :-)
Finally, I just use the retention policy on that list to delete emails after two weeks.
And by saving this list as a template, it's super easy to deploy it whereever I want.

I guess you understood that no, I won't add a SendEmail function because it doesn't seem necessary at this point !

Thanks for your suggestion anyway !
