### ISSUE TITLE
Consider augmenting the return set of values to account for ODATA_ prefix

### ISSUE THREAD

**Issue by Katydude** [Aymkdn/SharepointPlus#129]
I have a client who, not knowingly, created fields in his lists with special characters in very odd places. One such list item (column) begins with an underscore, e.g. _Category. When this value is returned by SharePoint's native JSOM, I believe it recognizes the special ODATA_ leader that is put onto the fieldname and adjusts accordingly. I would appreciate it if you would consider doing something similar in SharepointPlus. It would be very helpful to have access to a field by its recognized name, e.g. _Category rather than having to hack together code in my service layer to look for ODATA_ and strip it off or add it on. Or maybe you've encountered this already and have some other ideas about why it must stay as ODATA_... in your client-side library. Thanks for the consideration.

**Comment by Aymkdn** [comment]
I'm trying to understand. You have a field with a display name that is "Category", but the internal name of the field is actually "ODATA_Category"? 

When you use `$SP().list().get()` you have to use the internal names. They are easy to find by looking at the column's settings in Sharepoint: the internal name appears in the URL.
You could also use [`$SP().list().info()`](https://aymkdn.github.io/SharepointPlus/lists.html#info) to first retrieve the internal name of the column's and then use it for your `.get()`.

Here you're asking me if it's possible to add an option with `.get()` that will permit to use the **column's display names** instead of the internal names? I guess I could add that. In that case the `. info()` will automatically be done by `.get()` and map the information.
However, I don't think it's a good idea because it will cause a big issue: if the user renames the column you have to change your code.... 

Or maybe I didn't understand your question?! You said something about JSOM that removes the "ODATA_" part automatically?! I've never seen a field that includes this "ODATA_" part if it wasn't in the column's name in the first place.... So I'm not sure what it is...

**Comment by koltyakov** [comment]
It's not JSOM augmenting field names, but JSOM and REST (OData) operating different types of names. JSOM uses internal field names, but REST doesn't, it uses `EntityPropertyName` in the scope of its OData operations. In most of cases internal and entity property names are just the same. But when a data schema is a result of human actions with relying on display names it's common to end up with a difference. OData_ prefix is common; if the internal name starts with `_`, entity name starts with `OData_`.

![image](https://user-images.githubusercontent.com/7816483/71305498-4678e600-23e6-11ea-8909-a142f0bac4b7.png)

These fields should not be augmented with a client library as you also should use such names in OData modifiers and payloads.

The best approach is a map layer in the custom code. And recommending never creating artifacts manually, but using provisioning tools.

**Comment by Katydude** [comment]
I don't use display names for data interactivity. I don't know that it is even possible to do so with any client side library. Not sure why you would assume that.

The code I am using is
web.lists.getByTitle(xxx).getItemsByCAMLQuery(caml, 'FieldValuesAsText') 

My query for the internal name "_Category" will not result in either an error or data returned with this field name. Do you agree? At any rate, I just thought I would point it out. I appreciate the explanation of what is going on.

Seems like it would make sense to return to the user a field name matching what they queried for.  Obviously, if the middleware doesn't address this then the developer must do it (as I have) in the mapping layer for each application. 

![image](https://user-images.githubusercontent.com/32487742/71317157-6211da00-2442-11ea-8e3a-988170d577c9.png)

**Comment by Aymkdn** [comment]
> The code I am using is
> web.lists.getByTitle(xxx).getItemsByCAMLQuery(caml, 'FieldValuesAsText')

It's not a code related to SharepointPlus.

I tried to create a column named `_Category` in both Sharepoint 2013 OnProm and in Sharepoint Online, then my library looks OK to me:
```javascript
$SP().list("Tests").get({fields:"_Category"}).then(data => {
  console.log(data[0].getAttribute("_Category")); // it works
})
```

I'll close this issue as I don't see how it is related to SharepointPlus...

**Comment by Katydude** [comment]
I apologize. You are right. The project I am doing some work on has two different libraries referenced, yours and PNP/SP. It is the other one that muddles the names. I feel bad for wasting your time. Again, so sorry about that.
