### ISSUE TITLE
where clause on text with back slash \ requires 4 back slashes !!

### ISSUE THREAD

**Issue by Marouanebouzoubaa** [Aymkdn/SharepointPlus#136]
First, excellent work and keep up maintaining this project.

I encountered a weird problem where I have a text column with text like domain\abc
to make the where condition work, i had to encode the back slash twice like this !

where:"My_Field = 'domain\\\\\\\\abc'", 

I am not sure if this is the default behavior or a bug, but i found on the documentation of the Add function the following:
               note: A person must be provided as "-1;#email" (e.g. "-1;#foo@bar.com") OR NT login with double \ (eg "-1;#europe\\\\foo_bar") OR the user ID as a number

Is there a documentation that explains how the where works for different column types and wich operators can work with each column type. although the generated documentation is good enough, most of the time it is trial and error process. having also this documentation will make a better person.

Note: The editor for reporting the issue in github also shows two back slashes as one, so I had to double the number of slashes in the message to have the correct number shown.

Thx

**Comment by Aymkdn** [comment]
As you probably know, `\` is a special character in JavaScript (and other languages). It's why you need to have 2 `\\` in JavaScript to represent 1 `\` at the end.

Regarding your `'domain\\\\abc'`, it might be because the value is stored as `'domain\\abc'` so 4 `\` are required to return 2 `\`. I don't think it's a bug of SharepointPlus but more something related to the way your data is stored?!

> Is there a documentation that explains how the where works for different column types and wich operators can work with each column type

I'm not sure to understand this question. As you said, I gave some tips in [`$SP().list().add()`](https://aymkdn.github.io/SharepointPlus/lists.html#add) on how to deal with some special types. It's not something related to SharepointPlus but to how Sharepoint handles some column's types, that is not also simple…

> although the generated documentation is good enough, most of the time it is trial and error process. having also this documentation will make a better person.

I'm very sorry but I didn't understand this part… If you have an example of what you mean?

**Comment by Marouanebouzoubaa** [comment]
Hi, 

My data is stored with one and only one back slash as 'domain\abc', I have created another sample example to illustrate what i was saying. Please see below my test on chrome console showing two queries, the one with 4 slashes works whereas the one with two return 0 rows.
I suggest that you re-create the sample, maybe the versions of SP we using are different. I am using the browser version v6.1.1.
For my comment regarding the documentation, forget what I said, by practicing and doing more examples, I find all what i need.

![SharepointPlus query text with back slash](https://user-images.githubusercontent.com/37161616/83351558-f7dc5a00-a33c-11ea-979c-9d2606c58bd8.JPG)

Cheers,

**Comment by Aymkdn** [comment]
I'll have a look later this week (on Tuesday or Wednesday)

**Comment by Aymkdn** [comment]
I've just fixed it in v6.1.2

Thanks.

**Comment by Marouanebouzoubaa** [comment]
Tested the fix in v6.1.2, It works.

Thx.
