### ISSUE TITLE
Do you have an example code for using node-sp-auth to pull data from Shared Documents

### ISSUE THREAD

**Issue by anabwan** [Aymkdn/SharepointPlus#154]
Hi @Aymkdn,

Do you have and example code of using sharepointplus/dist and node-sp-auth (sharepoint365) in order to pull data from Shared Documents from my sharepoint ?

**Comment by Aymkdn** [comment]
You have an example in the documentation for the Shared Document https://aymkdn.github.io/SharepointPlus/lists.html#get

Regarding the authentication, you have to check https://aymkdn.github.io/SharepointPlus/node.html#auth 

For SP365, it depends your authentication method... Check their documentation https://github.com/s-KaiNet/node-sp-auth

I'll close the ticket because I cannot help more than that
