### ISSUE TITLE
CheckOut() method

### ISSUE THREAD

**Issue by beruken** [Aymkdn/SharepointPlus#18]
Is there a checkout() method? IF not how to update moderation status without this feature?

**Comment by Aymkdn** [comment]
No, there is no `checkout`. I don't see any reasons to have to checkout a file with JavaScript. The `checkin` is useful if you upload a file for example. And because I never needed it, I didn't code it :-)

So for the checkout, you may want to create your own jQuery.ajax() based on the [Microsoft documentation](https://msdn.microsoft.com/en-us/library/lists.lists.checkoutfile.aspx).
