### ISSUE TITLE
Update a multivalued field

### ISSUE THREAD

**Issue by p3u** [Aymkdn/SharepointPlus#19]
Hello,
First of all, thank you for the wonderful library you've made. It made my programming a lot easier.

I've been trying to find a way to update a multivalued field of an item on a SP list.
For example I've tried to update with lines such as:

`$SP().list("lst_Errors").update({ID:31, Risks: [570, 572]})`
`$SP().list("lst_Errors").update({ID:31, Risks: ;#570;#572;#"})`
`$SP().list("lst_Errors").update({ID:31, Risks: '570, 572'})`
`$SP().list("lst_Errors").update({ID:31, Risks: '#570; #572'})`

Is it possible to do what I'm trying?
Thank you very much.

**Comment by Aymkdn** [comment]
Hi,

If you look at the [`$SP().list().add() function`](http://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.list.html#.add) there are several examples of the format that Sharepoint uses.

So if it's just a "Choice" field (nothing fancy), you can use either the array `[]` or `;#570;#572;#` (if 570 and 572 are two of the options in the dropdown).

So if it didn't work it's probably because you don't use a "Choice" field but something else... What are the settings for that field ?

Note: I'm going on vacations starting today so except some delays on my reply

**Comment by p3u** [comment]
It's actually a lookup field pointing to the same table.
The numbers are the ID.

The lookup field is actually returning the title, let's called it 'Risk 1' and 'Risk 2', with ID's 570 and 572..

**Comment by Aymkdn** [comment]
So if you read the [documentation](http://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.list.html#.add) : ` A lookup value must be provided as "X;#value", with X the ID of the value from the lookup list.`

Then I think It should be something like : `$SP().list("lst_Errors").update({ID:31, Risks: ";#570;#Risk 1;#572;#Risk 2;#"})`

**Comment by p3u** [comment]
It worked! Thanks so much.
I was even able to update without passing the title! For some reason just by passing '#' instead of '#value' worked. e.g. `$SP().list("lst_Errors").update({ID:31, Risks: ";#570;#;#572;#;#"})`.

Thanks a lot for your help.
