### ISSUE TITLE
Pull List Values That Have Been Filtered

### ISSUE THREAD

**Issue by slhilbert** [Aymkdn/SharepointPlus#32]
I have a list that has been filtered by the user using the list filters.  Is it possible to pull out just the values of the filtered list?

Thanks!

**Comment by ocelotsloth** [comment]
If the list filter is done as a separate view you should be able to pull the view down with the API.
http://aymkdn.github.io/SharepointPlus/symbols/%24SP%28%29.list.html#.get
>
- String
- setup.view Optional, Default: ""
- If you specify a viewID or a viewName that exists for that list, then the fields/where/order settings for this view will be used in addition to the FIELDS/WHERE/ORDERBY you have defined (the user settings will be used first)

I'd give that a try. I can't test it till tomorrow when I have access to my environment since it's on intra-net, but if you want I can play with it for a few minutes. Assuming of course a solution isn't found by then.

**Comment by slhilbert** [comment]
Thanks ocelotsloth for the reply.  I have a view setup, but then the users are filtering it down in this case via state with the dropdownlist that is auto created in the list view.  I need to extract the user filtered list.  Does that make sense?  

Other approaches would be if I could grab the filters the users have applied and then build the WHERE clause in SharepointPlus.

**Comment by Aymkdn** [comment]
This doesn't seem related to SharepointPlus....

To find the filters used by the user, you can look at the URL. They show up into the URL parameters. Get them (with GetUrlKeyValue()) and use them to build the WHERE clause.
