### ISSUE TITLE
create a Excel file with hebrew characters

### ISSUE THREAD

**Issue by danbete** [Aymkdn/SharepointPlus#41]
hi, 
first thank you for the hard work :+1: 

ive just started to work with your library and im trying to export a table to xls but it seems like the encoding system you are using delete all hebrew (and posibly also arb)
the file is saved but the data is missing from the places were theres hebrew.

dan

**Comment by Aymkdn** [comment]
Hi

Do you have the code you're using please?

**Comment by danbete** [comment]
hi, im trying export any table with hebrew using 

<script>

var tableID = "ReportGrid";
var FileName = "Report";
var LibraryName = "Documents";

function exportXLS (){
  // get all the table
 // var tableHTML = $("#"+tableID)[0].outerHTML;
  var cont = exportTableToCSV($("#"+tableID))
  $SP().createFile({
  content:cont,
  filename:FileName+".xls",
  library:LibraryName ,
  url:"http://my-sp-site",
  after:function(fileURL) {
// download the file
    window.location.href=fileURL;
  }
});
}

</script>



table to test
<table id="testt" style="width:100%">
  <tr>
    <th>נסיון</th>
    <th>Lastname</th> 
    <th>Age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>בדיקה</td>
    <td>חמישים</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>שם משפחה</td>
    <td>גיל</td>
  </tr>
  <tr>
    <td>עוד בדיקה</td>
    <td>Doe</td>
    <td>בדיקה</td>
  </tr>
</table>

**Comment by danbete** [comment]
and this is the script...
`
<script>

var tableID = "ReportGrid";
var FileName = "NintexReport";
var LibraryName = "Documents";

function exportXLS (){
  // get all the table
 // var tableHTML = $("#"+tableID)[0].outerHTML;
  var cont = exportTableToCSV($("#"+tableID))
  $SP().createFile({
  content:cont,
  //encoded:1,
  filename:FileName+".csv",
  library:LibraryName ,
  url:"http://dev-sp-2013",
  after:function(fileURL) {
    window.location.href=fileURL;
  }
});
}

</script>`

**Comment by Aymkdn** [comment]
You can try to open your filename.xls into a text editor and to check the content.... The code you use is just sending the HTML code into a .xls file, and then Excel will open the HTML Table structure and convert it to Excel. Nothing else.
That could be a charset issue with Excel that doesn't read correctly the HTML table. In that case you can try to send a full HTML page with a `meta charset` instead of just sending your `<table>`, as shown here: http://stackoverflow.com/a/25730640/1134119

The other solution could be to use [ExcelPlus](http://aymkdn.github.io/ExcelPlus/) — this helper will create a true Excel file XLSX, and that could resolve the charset issue.

**Comment by Aymkdn** [comment]
Please keep me updated about it. Thanks.
