### ISSUE TITLE
Choice

### ISSUE THREAD

**Issue by adragton** [Aymkdn/SharepointPlus#98]
Don't see or understand how to GET choice value of field.
```javascript
$SP().list("tbl_information").get().then(function (data) {
  for (var i=0; i<data.length; i++)
 {
  alert(data[i].getAttribute("Lifecycle_Phase"));
  }
});
```
===============
Lifecycle_Phase:
Open
Closed
Followup

**Comment by Aymkdn** [comment]
Are you looking for the choices defined for the field settings, or the current values used in your list?

Because `get()` retrieves the data from the list, so you'll only get the values selected from your items.

If you search for ALL the options defined in the field settings, then you have to use [`.info()`](https://aymkdn.github.io/SharepointPlus/lists.html#info)

**Comment by adragton** [comment]
Aymeric

Thank you for your quick reply.

Yes, I am trying to get the value that resides in the list after a selection for the field has been saved to list.

However, I tried the .info(), and the alert did not produce any results.


$SP().list("tbl_information").info().then(function(data)

  {

  for (var i=0; i<data.length; i++) {
  alert(data[i].getAttribute("test99"))
  }
});

________________________________

**Comment by Aymkdn** [comment]
You don't use `info()` correctly. Please read correctly [the documentation](https://aymkdn.github.io/SharepointPlus/lists.html#info)

**Comment by adragton** [comment]
Thank you.
Yes that finally did work.

Still the choice, not displaying in alert !!
Is the syntax I used wrong ??

Allan Dragton

________________________________

**Comment by Aymkdn** [comment]
> Is the syntax I used wrong ??

Everything is wrong in the way you used `info()`.

**Comment by adragton** [comment]
Sorry, I am not clear.

I need value that was selected from choice field.
The .get syntax not working.

Allan Dragton

**Comment by Aymkdn** [comment]
I'm sorry but I don't understand. Please provide more details / examples.

**Comment by adragton** [comment]
ok, here is the syntax I am using-
$SP().list("tbl_information").get().then(function(data)
  {
  for (var i=0; i<data.length; i++) {
  alert(data[i].getAttribute("status"))
  }
});


I am trying to get the value from a "choice" column.

There are 3 choice-values in the list:

Complete

Draft

Audit


Is the above syntax correct to get a value in a choice column ?

________________________________

**Comment by Aymkdn** [comment]
(Please use this link https://github.com/Aymkdn/SharepointPlus/issues/98 instead of replying by email !!)

Let's take an example...

Let's say you have a list with two columns : 

1. Column "Title"
2. Column "status" that is a Choice selection (Dropdown) with 3 options: "Audit", "Draft" and "Complete"

You first need to make sure that **status** is the correct internal name for your column. To verify, just go to the List Settings and click on the **status** column, then check the last part of URL. For example: 
> https://your.sharepoint.com/your_site/_layouts/15/FldEdit.aspx?List=%7B6C523E23%2DA741%2D40A1%2D98AE%2D058A2A707E7C%7D&Field=Category
Here the internal name for the field is **Category** (because the URL finishes with **Field=Category**).

Let's now say you have 5 items into your list. They are the below:

| ID        | Title           | status  |
| ------- |:-----------:| -------:|
| 1   | demo1 | Audit |
| 2 | demo2 | Audit |
| 3 | demo3 | Complete |
| 4 | demo4 | Draft |
| 5 | demo5 | Complete |

Now, let's say you want to retrieve the above data:
You'll do it this way:
```javascript
$SP().list("tbl_information").get({
  fields:"ID,Title,status"
})
.then(function(data) {
  for (var i=0; i<data.length; i++) {
    console("For #"+data[i].getAttribute("ID")+" the status is: "+data[i].getAttribute("status"))
  }
});

/*
Result:
 - For #1 the status is Audit
 - For #2 the status is Audit
 - For #3 the status is Complete
 - For #4 the status is Draft
 - For #5 the status is Complete
*/
```

**Comment by Aymkdn** [comment]
No reply after 4 days. I close the issue.

**Comment by adragton** [comment]
Yes
Close issue.
Your suggestion olved problem.
Thank you !!

Allan Dragton

________________________________
